### PR TITLE
Cast all header types into strings before handing to requests

### LINKED ISSUE #83: Header value types in Python3.5 fail requests validation
We've recently migrated to Python 3.5, and are observing the following stack trace when making docdb requests:
```
...
  File "/Users/brmatt/Development/infra/acmcloud/accloud/utils/superpod_config_db.py", line 41, in status_doc
    self._status_doc = self.docdb_client.ReadDocument(self.superpod_status_doc)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/document_client.py", line 944, in ReadDocument
    options)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/document_client.py", line 2244, in Read
    url_connection = self._global_endpoint_manager.ReadEndpoint
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/global_endpoint_manager.py", line 48, in ReadEndpoint
    self.RefreshEndpointList()
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/global_endpoint_manager.py", line 67, in RefreshEndpointList
    database_account = self._GetDatabaseAccount()
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/global_endpoint_manager.py", line 85, in _GetDatabaseAccount
    database_account = self._GetDatabaseAccountStub(self.DefaultEndpoint)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/global_endpoint_manager.py", line 105, in _GetDatabaseAccountStub
    return self.Client.GetDatabaseAccount(endpoint)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/document_client.py", line 2082, in GetDatabaseAccount
    headers)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/document_client.py", line 2309, in __Get
    headers)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/synchronized_request.py", line 206, in SynchronizedRequest
    return retry_utility._Execute(client, global_endpoint_manager, _Request, connection_policy, requests_session, resource_url, request_options, request_body)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/retry_utility.py", line 51, in _Execute
    result = _ExecuteFunction(function, *args, **kwargs)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/retry_utility.py", line 85, in _ExecuteFunction
    return function(*args, **kwargs)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/pydocumentdb/synchronized_request.py", line 122, in _Request
    verify = is_ssl_enabled)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 303, in prepare
    self.prepare_headers(headers)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 427, in prepare_headers
    check_header_validity(header)
  File "/Users/brmatt/Development/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/utils.py", line 796, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 0 must be of type str or bytes, not <class 'int'>
```

(the header field that is causing the error in this particular case is ContentLength, set around line 198 of synchronized_request.py; forcibly setting the type here exposes other similar type problems in other header values)

This is observed using:
* python 3.5.2
* requests 2.12.4

### PR DESCRIPTION
**Pull request by thenewwazoo**
Fixes #83

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thenewwazoo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brmatt). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by thenewwazoo** [comment]
I did a cursory test with Python 2.7.13 and it appears to cause no problems.

**Comment by rnagpal** [comment]
@thenewwazoo Can you also update requirements.txt to change requests==2.10.0 to requests>=2.10.0 as well?
Also, in setup.py:
 install_requires=['six >=1.6', 'requests==2.10.0'], to
 install_requires=['six >=1.6', 'requests>=2.10.0'],

@moderakh Do you know anything else that needs to be updated?

**Comment by moderakh** [comment]
```
$ grep requests -r . | grep 2.10
./requirements.txt:requests==2.10.0
./setup.py:      install_requires=['six >=1.6', 'requests==2.10.0'],
```
@rnagpal requirements.txt and setup.py are the only two files pointing to the specific requests library version.

**Comment by rnagpal** [comment]
@thenewwazoo Please ensure that all existing tests pass with your change.

**Comment by rnagpal** [comment]
@thenewwazoo Please incorporate my comment and ensure that all tests are passing so that we can merge this PR.

**Comment by rnagpal** [comment]
@thenewwazoo I see that you closed this PR. Didn't you wanted to merge this in our repo?

**Pull request closed without merging**
