### PR TITLE
Add "populateQueryMetrics" option to queries.

### PR DESCRIPTION
**Pull request by austindonnelly**
This requests the server to provide query performance metrics in client.last_response_headers.
This helps when doing performance debugging of queries.

### CODE REVIEW

**Comment by kirankumarkolli** [comment]
@moderakh @srinathnarayanan can you take a look at this?

**Comment by moderakh** [comment]
@austindonnelly thanks for you contribution. Can you please add a simple unit test?

**Comment by austindonnelly** [comment]
Ok, I've added a test which runs a query, specifiying the new option to request query metrics.  It then checks the server really did return the metrics, and that they are in a the expected form: key=value;key=value.

**Comment by austindonnelly** [comment]
Any progress on this? I merged with current upstream so this pull request is still up to date.

**Comment by austindonnelly** [comment]
Any more comments?  Can this be merged to master?

**Comment by austindonnelly** [comment]
Any more comments?  Can this be merged to master?

**Comment by moderakh** [comment]
@austindonnelly thank you. Looks good. I am merging the PR.

**Pull request merged**
